# Generated by Django 4.2.2 on 2023-07-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_files',
            name='display_picture',
            field=models.FileField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
