# Generated by Django 4.2.3 on 2023-07-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_uploaded_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_files',
            name='Title',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
