# Generated by Django 4.2.3 on 2023-07-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_ver_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ver_otp',
        ),
    ]
