# Generated by Django 4.2.3 on 2023-07-10 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_delete_ver_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_files',
            name='display_picture',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
