# Generated by Django 4.2.3 on 2023-07-10 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_uploaded_files_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_files',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
